title: "Raimana RATARO-TUIHAA — Portfolio"
email: "ratarotahiti@icloud.com"
description: "Ingénieur en océanographie & télédétection — Portfolio professionnel."
baseurl: ""
url: "https://tonpseudo.github.io"
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
